secret_key_base: 043de26b0206fdbfd6b33291b9abb34e50a756ad4863a3024542c5eea4856d40c5c32e3b186cdc93c5ca370f4ac17b0e1a0ddd53716b3b0e7eb13030e709136c
twilio_account_sid:  <%= ENV.fetch("TWILIO_ACCOUNT_SID", "ACb037f1792aba3912de71bf85cd48fe59") %>
twilio_auth_token:  <%= ENV.fetch("TWILIO_AUTH_TOKEN", "715f26534197ed0c52b9af8313f590e7") %>
twilio_phone_number:  <%= ENV.fetch("TWILIO_PHONE_NUMBER", "+13184318815") %>



